version: 0.2  
env: 
  secrets-manager:
    username: testing/sonar:username
    token: testing/sonar:token
phases:
  pre_build:
    commands:
      - echo installing dependencies
      - chmod +x ./scripts/awscli.sh
      - chmod +x ./scripts/eksctl.sh
      - chmod +x ./scripts/kubectl.sh
      - ./scripts/awscli.sh
      - ./scripts/eksctl.sh
      - ./scripts/kubectl.sh
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 185633157927.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker login -u $username -p $token
      - echo login success
      - docker build -t varthana1 .
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker tag varthana1:latest 185633157927.dkr.ecr.ap-south-1.amazonaws.com/varthana:latest
      - docker push 185633157927.dkr.ecr.ap-south-1.amazonaws.com/varthana:latest
      - chmod +x ./scripts/clustercreate.sh
      - ./scripts/clustercreate.sh    
      - kubectl apply -f springboot.yaml

