version: 0.2
phases:
  pre_build:
    commands:
      - echo "Running kubelinter for Kubernetes configuration checks..."
      - wget -O kubelinter https://github.com/stackrox/kube-linter/releases/download/v0.6.8/kube-linter-linux
      - chmod +x kubelinter
      - kubelinter lint -o kubernetes springboot.yaml
