apiVersion: apps/v1
kind: Deployment
metadata:
  name: varthana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varthana
  template:
    metadata:
      labels:
        app: varthana
    spec:
      containers:
      - name: varthana
        image: 
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: varthana-service
spec:
  selector:
    app: varthana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer
